{
    "name":"Bahmni Custom For Gudalur2",
    "version":"1.0",
    "author":"ThoughtWorks Technologies Pvt. Ltd.",
    "category":"BahmniCustom",
    "description":"Custom changes for gudalur environment",
    "depends": ["base","sale","account","bahmni_sale"], 
    #"bahmni_customer_payment","account","bahmni_internal_stock_move","bahmni_pharmacy_product","bahmni_purchase_extension","bahmni_stock_batch_sale_price","bahmni_sale_discount","sale","stock","purchase","account"],
    'data':[
         'security/ir.model.access.csv',
         'attribute_in_sale_order.xml',
         'price_in_stock_product_lot.xml',
         'claim_type.xml',
         'sale_order_type_shop_form.xml',
         'sale_care_setting_form.xml',
         'product_category_department.xml',
         'chargetype_category_mapping.xml',
         'product_schedule_h_form.xml',
         'products_by_last_moved_view.xml',
         'stock_location_prod_lot_view.xml',
         'stock_view.xml',
         'module_misc.xml',
         'filters.xml',
         'product_temp.xml',
         'stock_production_lot.xml',
         'data/scheduler.xml'
    ],
    'demo':[],
    'auto_install':False,
    'application':True,
    'installable':True,
}
